SELECT USER_ID, PRODUCT_ID
FROM (
        SELECT USER_ID, PRODUCT_ID, count(*) as counts
        FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID
) as C_TABLE
WHERE counts > 1 
ORDER BY USER_ID, PRODUCT_ID DESC;
