-- 코드를 입력하세요
-- REST_INFO
-- REST_REVIEW 

SELECT
    A.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES, 
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE),2) AS SCORE
    
FROM REST_INFO A
    JOIN REST_REVIEW B USING (REST_ID)
    
WHERE A.ADDRESS LIKE '서울%'
GROUP BY 
    A.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;