-- 코드를 입력하세요
-- 상반기 주문 정보가 3000 보다 높은 
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER >= 3000 AND ICECREAM_INFO.INGREDIENT_TYPE ='fruit_based'
ORDER BY TOTAL_ORDER DESC; 